/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PatientIndexRouteImport } from './routes/patient/index'
import { Route as HospitalIndexRouteImport } from './routes/hospital/index'
import { Route as EmtIndexRouteImport } from './routes/emt/index'
import { Route as PatientSosRouteImport } from './routes/patient/sos'
import { Route as PatientQrRouteImport } from './routes/patient/qr'
import { Route as PatientProfileRouteImport } from './routes/patient/profile'
import { Route as NTokenRouteImport } from './routes/n.$token'
import { Route as EmtScanRouteImport } from './routes/emt/scan'
import { Route as ETokenRouteImport } from './routes/e.$token'
import { Route as PatientSessionIdRouteImport } from './routes/patient/session.$id'
import { Route as HospitalIncidentIdRouteImport } from './routes/hospital/incident.$id'
import { Route as EmtSessionIdRouteImport } from './routes/emt/session.$id'
import { Route as ApiPublicSeedRouteImport } from './routes/api/public/seed'
import { Route as ApiPublicDemoResetRouteImport } from './routes/api/public/demo-reset'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientIndexRoute = PatientIndexRouteImport.update({
  id: '/patient/',
  path: '/patient/',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalIndexRoute = HospitalIndexRouteImport.update({
  id: '/hospital/',
  path: '/hospital/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmtIndexRoute = EmtIndexRouteImport.update({
  id: '/emt/',
  path: '/emt/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientSosRoute = PatientSosRouteImport.update({
  id: '/patient/sos',
  path: '/patient/sos',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientQrRoute = PatientQrRouteImport.update({
  id: '/patient/qr',
  path: '/patient/qr',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientProfileRoute = PatientProfileRouteImport.update({
  id: '/patient/profile',
  path: '/patient/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NTokenRoute = NTokenRouteImport.update({
  id: '/n/$token',
  path: '/n/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const EmtScanRoute = EmtScanRouteImport.update({
  id: '/emt/scan',
  path: '/emt/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const ETokenRoute = ETokenRouteImport.update({
  id: '/e/$token',
  path: '/e/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientSessionIdRoute = PatientSessionIdRouteImport.update({
  id: '/patient/session/$id',
  path: '/patient/session/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalIncidentIdRoute = HospitalIncidentIdRouteImport.update({
  id: '/hospital/incident/$id',
  path: '/hospital/incident/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EmtSessionIdRoute = EmtSessionIdRouteImport.update({
  id: '/emt/session/$id',
  path: '/emt/session/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSeedRoute = ApiPublicSeedRouteImport.update({
  id: '/api/public/seed',
  path: '/api/public/seed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDemoResetRoute = ApiPublicDemoResetRouteImport.update({
  id: '/api/public/demo-reset',
  path: '/api/public/demo-reset',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/e/$token': typeof ETokenRoute
  '/emt/scan': typeof EmtScanRoute
  '/n/$token': typeof NTokenRoute
  '/patient/profile': typeof PatientProfileRoute
  '/patient/qr': typeof PatientQrRoute
  '/patient/sos': typeof PatientSosRoute
  '/emt/': typeof EmtIndexRoute
  '/hospital/': typeof HospitalIndexRoute
  '/patient/': typeof PatientIndexRoute
  '/api/public/demo-reset': typeof ApiPublicDemoResetRoute
  '/api/public/seed': typeof ApiPublicSeedRoute
  '/emt/session/$id': typeof EmtSessionIdRoute
  '/hospital/incident/$id': typeof HospitalIncidentIdRoute
  '/patient/session/$id': typeof PatientSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/e/$token': typeof ETokenRoute
  '/emt/scan': typeof EmtScanRoute
  '/n/$token': typeof NTokenRoute
  '/patient/profile': typeof PatientProfileRoute
  '/patient/qr': typeof PatientQrRoute
  '/patient/sos': typeof PatientSosRoute
  '/emt': typeof EmtIndexRoute
  '/hospital': typeof HospitalIndexRoute
  '/patient': typeof PatientIndexRoute
  '/api/public/demo-reset': typeof ApiPublicDemoResetRoute
  '/api/public/seed': typeof ApiPublicSeedRoute
  '/emt/session/$id': typeof EmtSessionIdRoute
  '/hospital/incident/$id': typeof HospitalIncidentIdRoute
  '/patient/session/$id': typeof PatientSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/e/$token': typeof ETokenRoute
  '/emt/scan': typeof EmtScanRoute
  '/n/$token': typeof NTokenRoute
  '/patient/profile': typeof PatientProfileRoute
  '/patient/qr': typeof PatientQrRoute
  '/patient/sos': typeof PatientSosRoute
  '/emt/': typeof EmtIndexRoute
  '/hospital/': typeof HospitalIndexRoute
  '/patient/': typeof PatientIndexRoute
  '/api/public/demo-reset': typeof ApiPublicDemoResetRoute
  '/api/public/seed': typeof ApiPublicSeedRoute
  '/emt/session/$id': typeof EmtSessionIdRoute
  '/hospital/incident/$id': typeof HospitalIncidentIdRoute
  '/patient/session/$id': typeof PatientSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo'
    | '/login'
    | '/signup'
    | '/e/$token'
    | '/emt/scan'
    | '/n/$token'
    | '/patient/profile'
    | '/patient/qr'
    | '/patient/sos'
    | '/emt/'
    | '/hospital/'
    | '/patient/'
    | '/api/public/demo-reset'
    | '/api/public/seed'
    | '/emt/session/$id'
    | '/hospital/incident/$id'
    | '/patient/session/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo'
    | '/login'
    | '/signup'
    | '/e/$token'
    | '/emt/scan'
    | '/n/$token'
    | '/patient/profile'
    | '/patient/qr'
    | '/patient/sos'
    | '/emt'
    | '/hospital'
    | '/patient'
    | '/api/public/demo-reset'
    | '/api/public/seed'
    | '/emt/session/$id'
    | '/hospital/incident/$id'
    | '/patient/session/$id'
  id:
    | '__root__'
    | '/'
    | '/demo'
    | '/login'
    | '/signup'
    | '/e/$token'
    | '/emt/scan'
    | '/n/$token'
    | '/patient/profile'
    | '/patient/qr'
    | '/patient/sos'
    | '/emt/'
    | '/hospital/'
    | '/patient/'
    | '/api/public/demo-reset'
    | '/api/public/seed'
    | '/emt/session/$id'
    | '/hospital/incident/$id'
    | '/patient/session/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoRoute: typeof DemoRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ETokenRoute: typeof ETokenRoute
  EmtScanRoute: typeof EmtScanRoute
  NTokenRoute: typeof NTokenRoute
  PatientProfileRoute: typeof PatientProfileRoute
  PatientQrRoute: typeof PatientQrRoute
  PatientSosRoute: typeof PatientSosRoute
  EmtIndexRoute: typeof EmtIndexRoute
  HospitalIndexRoute: typeof HospitalIndexRoute
  PatientIndexRoute: typeof PatientIndexRoute
  ApiPublicDemoResetRoute: typeof ApiPublicDemoResetRoute
  ApiPublicSeedRoute: typeof ApiPublicSeedRoute
  EmtSessionIdRoute: typeof EmtSessionIdRoute
  HospitalIncidentIdRoute: typeof HospitalIncidentIdRoute
  PatientSessionIdRoute: typeof PatientSessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/': {
      id: '/patient/'
      path: '/patient'
      fullPath: '/patient/'
      preLoaderRoute: typeof PatientIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospital/': {
      id: '/hospital/'
      path: '/hospital'
      fullPath: '/hospital/'
      preLoaderRoute: typeof HospitalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emt/': {
      id: '/emt/'
      path: '/emt'
      fullPath: '/emt/'
      preLoaderRoute: typeof EmtIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/sos': {
      id: '/patient/sos'
      path: '/patient/sos'
      fullPath: '/patient/sos'
      preLoaderRoute: typeof PatientSosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/qr': {
      id: '/patient/qr'
      path: '/patient/qr'
      fullPath: '/patient/qr'
      preLoaderRoute: typeof PatientQrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/profile': {
      id: '/patient/profile'
      path: '/patient/profile'
      fullPath: '/patient/profile'
      preLoaderRoute: typeof PatientProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/n/$token': {
      id: '/n/$token'
      path: '/n/$token'
      fullPath: '/n/$token'
      preLoaderRoute: typeof NTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emt/scan': {
      id: '/emt/scan'
      path: '/emt/scan'
      fullPath: '/emt/scan'
      preLoaderRoute: typeof EmtScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e/$token': {
      id: '/e/$token'
      path: '/e/$token'
      fullPath: '/e/$token'
      preLoaderRoute: typeof ETokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/session/$id': {
      id: '/patient/session/$id'
      path: '/patient/session/$id'
      fullPath: '/patient/session/$id'
      preLoaderRoute: typeof PatientSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospital/incident/$id': {
      id: '/hospital/incident/$id'
      path: '/hospital/incident/$id'
      fullPath: '/hospital/incident/$id'
      preLoaderRoute: typeof HospitalIncidentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emt/session/$id': {
      id: '/emt/session/$id'
      path: '/emt/session/$id'
      fullPath: '/emt/session/$id'
      preLoaderRoute: typeof EmtSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/seed': {
      id: '/api/public/seed'
      path: '/api/public/seed'
      fullPath: '/api/public/seed'
      preLoaderRoute: typeof ApiPublicSeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/demo-reset': {
      id: '/api/public/demo-reset'
      path: '/api/public/demo-reset'
      fullPath: '/api/public/demo-reset'
      preLoaderRoute: typeof ApiPublicDemoResetRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoRoute: DemoRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ETokenRoute: ETokenRoute,
  EmtScanRoute: EmtScanRoute,
  NTokenRoute: NTokenRoute,
  PatientProfileRoute: PatientProfileRoute,
  PatientQrRoute: PatientQrRoute,
  PatientSosRoute: PatientSosRoute,
  EmtIndexRoute: EmtIndexRoute,
  HospitalIndexRoute: HospitalIndexRoute,
  PatientIndexRoute: PatientIndexRoute,
  ApiPublicDemoResetRoute: ApiPublicDemoResetRoute,
  ApiPublicSeedRoute: ApiPublicSeedRoute,
  EmtSessionIdRoute: EmtSessionIdRoute,
  HospitalIncidentIdRoute: HospitalIncidentIdRoute,
  PatientSessionIdRoute: PatientSessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
