ALTER TYPE public.audit_action ADD VALUE IF NOT EXISTS 'TRANSCRIPT_VALIDATION_FAILED';
ALTER TYPE public.audit_action ADD VALUE IF NOT EXISTS 'AI_SUMMARY_VALIDATION_FAILED';
ALTER TYPE public.audit_action ADD VALUE IF NOT EXISTS 'MANUAL_INCIDENT_ASSESSMENT';